server:
  port: 8080
  servlet:
    context-path: /schoolNew
spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/news?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
      username: root
      password: 123215
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
    password: 123215

  servlet:
    multipart:
      max-file-size: 500000000
      max-request-size: 500000000

mybatis:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: com.chuanqihou.schoolnews.entity
com:
  chuanqihou:
    schoolnews:
      snowflake:
        machine-id: 1
        data-center-id: 1

